// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TiendaServicios.Api.Compra.Persistencia;

namespace TiendaServicios.Api.Compra.Migrations
{
    [DbContext(typeof(CarritoContexto))]
    [Migration("20200814115352_MigracionMySqlInicial")]
    partial class MigracionMySqlInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TiendaServicios.Api.Compra.Modelo.CarritoSession", b =>
                {
                    b.Property<int>("CarritoSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CarritoSessionId");

                    b.ToTable("CarritoSession");
                });

            modelBuilder.Entity("TiendaServicios.Api.Compra.Modelo.CarritoSessionDetalle", b =>
                {
                    b.Property<int>("CarritoSessionDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CarritoSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProductoSeleccionado")
                        .HasColumnType("text");

                    b.HasKey("CarritoSessionDetalleId");

                    b.HasIndex("CarritoSessionId");

                    b.ToTable("CarritoSessionDetalle");
                });

            modelBuilder.Entity("TiendaServicios.Api.Compra.Modelo.CarritoSessionDetalle", b =>
                {
                    b.HasOne("TiendaServicios.Api.Compra.Modelo.CarritoSession", "CarritoSession")
                        .WithMany("ListaDetalle")
                        .HasForeignKey("CarritoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
